# Generated by Django 3.1.4 on 2021-02-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='e_money',
            field=models.IntegerField(default=0, verbose_name='적립금'),
        ),
    ]
