# Generated by Django 3.1.4 on 2021-03-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_e_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_key',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
