# Generated by Django 3.1.4 on 2021-01-16 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.AddField(
            model_name='product',
            name='guide',
            field=models.CharField(max_length=200, null=True, verbose_name='안내사항'),
        ),
        migrations.AddField(
            model_name='product',
            name='one_description',
            field=models.TextField(blank=True, verbose_name='한줄설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='상품설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='가격'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d', verbose_name='메인 이미지')),
                ('sub_image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d', verbose_name='서브 이미지')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['product'],
            },
        ),
    ]
