# Generated by Django 3.1.4 on 2021-01-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210116_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='main_image',
            field=models.ImageField(default='products/no_image.png', upload_to='products/mainImage/%Y/%m/%d', verbose_name='메인 이미지'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sub_image',
            field=models.ImageField(default='products/no_image.png', upload_to='products/subImage/%Y/%m/%d', verbose_name='서브 이미지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='one_description',
            field=models.CharField(blank=True, max_length=150, verbose_name='한줄설명'),
        ),
    ]
