# Generated by Django 3.1.4 on 2021-01-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210114_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
