# Generated by Django 3.1.4 on 2021-02-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykurly', '0007_auto_20210223_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(default=1, max_length=20, verbose_name='배송 유형'),
            preserve_default=False,
        ),
    ]
