# Generated by Django 3.1.4 on 2021-02-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykurly', '0008_auto_20210223_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='basic_address',
            field=models.BooleanField(default=False, verbose_name='기본 배송지'),
        ),
    ]
