# Generated by Django 3.1.4 on 2021-02-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_e_money'),
        ('mykurly', '0010_auto_20210224_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='basic_address',
            field=models.BooleanField(default=False, null=True, verbose_name='기본 배송지 설정'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='calling',
            field=models.CharField(max_length=20, null=True, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(max_length=20, null=True, verbose_name='배송 유형'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='받을 사람'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
