# Generated by Django 3.1.4 on 2021-02-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykurly', '0011_auto_20210224_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='count',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='calling',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='받을 사람'),
        ),
    ]
