# Generated by Django 3.1.4 on 2021-01-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210120_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='p_id',
            field=models.PositiveIntegerField(null=True, verbose_name='아이디'),
        ),
    ]
