# Generated by Django 3.1.4 on 2021-01-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_photo_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='p_id',
        ),
        migrations.AddField(
            model_name='product',
            name='p_id',
            field=models.PositiveIntegerField(null=True, verbose_name='아이디'),
        ),
    ]
