# Generated by Django 3.1.4 on 2021-03-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='총 결제 금액'),
        ),
    ]
