# Generated by Django 3.1.4 on 2021-03-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_product_price',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='총 상품 금액'),
        ),
    ]
