# Generated by Django 3.1.4 on 2021-03-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_total_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='결제완료', max_length=100, verbose_name='주문상태'),
        ),
    ]
