# Generated by Django 3.1.4 on 2021-03-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='주문 상품 이름'),
            preserve_default=False,
        ),
    ]
