# Generated by Django 3.1.4 on 2021-01-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210107_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(editable=False, null=True, verbose_name='나이'),
        ),
    ]
